#!/usr/bin/env python3
from devkit.cli import app
from devkit.introspect import typer_reference

ref = typer_reference(app)
print("# Command Reference\n")
print("> This file is auto-generated. Do not edit by hand.\n")
for cmd in ref["commands"]:
    print(f"## {cmd['name']}\n")
    if cmd.get("help"):
        print(cmd["help"], "\n")
    if cmd.get("params"):
        print("**Parameters**:\n")
        for p in cmd["params"]:
            req = "(required)" if p.get("required") else ""
            print(f"- `{p['name']}` {req} – type: {p['param_type']} (default: {p['default']})")
    print()

print("\n---\n\nGenerated by `scripts/generate_reference.py`.\n")
